const wordBank = ['Lion', 'Lion',
                  'Tiger', 'Tiger',
                  'Elephant', 'Elephant',
                  'Giraffe', 'Giraffe',
                  'Zebra', 'Zebra', 
                  'Panda', 'Panda',
                  'Monkey', 'Monkey', 
                  'Kangaroo', 'Kangaroo',
                  'Bear', 'Bear', 
                  'Wolf', 'Wolf',
                  'Fox', 'Fox', 
                  'Deer', 'Deer',
                  'Rabbit', 'Rabbit', 
                  'Otter', 'Otter',
                  'Hippopotamus', 'Hippopotamus', 
                  'Rhinoceros', 'Rhinoceros',
                  'Dog', 'Dog',
                  'Cat', 'Cat',
                  'Hamster', 'Hamster',
                  'Sloth', 'Sloth',
                  'Dinosaur', 'Dinosaur',
                  'Lizard', 'Lizard',
                  'Camel', 'Camel',
                  'Koala', 'Koala',
                  'Raccoon', 'Raccoon'
                ];